  { "ab", "abk", "abk", "Abkhazian"},
  { "", "ace", "ace", "Achinese"},
  { "", "ach", "ach", "Acoli"},
  { "", "ada", "ada", "Adangme"},
  { "aa", "aar", "aar", "Afar"},
  { "", "afh", "afh", "Afrihili"},
  { "af", "afr", "afr", "Afrikaans"},
  { "", "afa", "afa", "Afro-Asiatic (Other)"},
  { "", "aka", "aka", "Akan"},
  { "", "akk", "akk", "Akkadian"},
  { "sq", "sqi", "alb", "Albanian"},
  { "", "ale", "ale", "Aleut"},
  { "", "alg", "alg", "Algonquian languages"},
  { "", "ajm", "ajm", "Aljamia"},
  { "", "tut", "tut", "Altaic (Other)"},
  { "am", "amh", "amh", "Amharic"},
  { "", "apa", "apa", "Apache languages"},
  { "ar", "ara", "ara", "Arabic"},
  { "", "arc", "arc", "Aramaic"},
  { "", "arp", "arp", "Arapaho"},
  { "", "arn", "arn", "Araucanian"},
  { "", "arw", "arw", "Arawak"},
  { "hy", "hye", "arm", "Armenian"},
  { "", "art", "art", "Artificial (Other)"},
  { "as", "asm", "asm", "Assamese"},
  { "", "ath", "ath", "Athapascan languages"},
  { "", "aus", "aus", "Australian languages"},
  { "", "map", "map", "Austronesian (Other)"},
  { "", "ava", "ava", "Avaric"},
  { "", "ave", "ave", "Avestan"},
  { "", "awa", "awa", "Awadhi"},
  { "ay", "aym", "aym", "Aymara"},
  { "az", "aze", "aze", "Azerbaijani"},
  { "", "nah", "nah", "Aztec"},
  { "", "ban", "ban", "Balinese"},
  { "", "bat", "bat", "Baltic (Other)"},
  { "", "bal", "bal", "Baluchi"},
  { "", "bam", "bam", "Bambara"},
  { "", "bai", "bai", "Bamileke languages"},
  { "", "bad", "bad", "Banda"},
  { "", "bnt", "bnt", "Bantu (Other)"},
  { "", "bas", "bas", "Basa"},
  { "ba", "bak", "bak", "Bashkir"},
  { "eu", "eus", "baq", "Basque"},
  { "", "btk", "btk", "Batak (Indonesia)"},
  { "", "bej", "bej", "Beja"},
  { "", "bem", "bem", "Bemba"},
  { "bn", "ben", "ben", "Bengali"},
  { "", "ber", "ber", "Berber (Other)"},
  { "", "bho", "bho", "Bhojpuri"},
  { "bh", "bih", "bih", "Bihari"},
  { "", "bik", "bik", "Bikol"},
  { "", "bin", "bin", "Bini"},
  { "bi", "bis", "bis", "Bislama"},
  { "", "bra", "bra", "Braj"},
  { "br", "bre", "bre", "Breton"},
  { "", "bug", "bug", "Buginese"},
  { "bg", "bul", "bul", "Bulgarian"},
  { "", "bua", "bua", "Buriat"},
  { "my", "mya", "bur", "Burmese"},
  { "be", "bel", "bel", "Byelorussian"},
  { "", "cad", "cad", "Caddo"},
  { "", "car", "car", "Carib"},
  { "ca", "cat", "cat", "Catalan"},
  { "", "cau", "cau", "Caucasian (Other)"},
  { "", "ceb", "ceb", "Cebuano"},
  { "", "cel", "cel", "Celtic (Other)"},
  { "", "cai", "cai", "Central American Indian (Other)"},
  { "", "chg", "chg", "Chagatai"},
  { "", "cmc", "cmc", "Chamic languages"},
  { "", "cha", "cha", "Chamorro"},
  { "", "che", "che", "Chechen"},
  { "", "chr", "chr", "Cherokee"},
  { "", "chy", "chy", "Cheyenne"},
  { "", "chb", "chb", "Chibcha"},
  { "zh", "zho", "chi", "Chinese"},
  { "", "chn", "chn", "Chinook jargon"},
  { "", "chp", "chp", "Chipewyan"},
  { "", "cho", "cho", "Choctaw"},
  { "", "chu", "chu", "Church Slavic"},
  { "", "chk", "chk", "Chuukese"},
  { "", "chv", "chv", "Chuvash"},
  { "", "cop", "cop", "Coptic"},
  { "", "cor", "cor", "Cornish"},
  { "co", "cos", "cos", "Corsican"},
  { "", "cre", "cre", "Cree"},
  { "", "mus", "mus", "Creek"},
  { "", "crp", "crp", "Creoles and pidgins (Other)"},
  { "", "cpe", "cpe", "Creoles and pidgins, English-based (Other)"},
  { "", "cpf", "cpf", "Creoles and pidgins, French-based (Other)"},
  { "", "cpp", "cpp", "Creoles and pidgins, Portuguese-based (Other)"},
  { "hr", "hrv", "scr", "Croatian"},
  { "", "cus", "cus", "Cushitic (Other)"},
  { "cs", "ces", "cze", "Czech"},
  { "", "dak", "dak", "Dakota"},
  { "da", "dan", "dan", "Danish"},
  { "", "day", "day", "Dayak"},
  { "", "del", "del", "Delaware"},
  { "", "din", "din", "Dinka"},
  { "", "div", "div", "Divehi"},
  { "", "doi", "doi", "Dogri"},
  { "", "dgr", "dgr", "Dogrib"},
  { "", "dra", "dra", "Dravidian (Other)"},
  { "", "dua", "dua", "Duala"},
  { "", "dum", "dum", "Dutch, Middle (ca. 1050-1350)"},
  { "nl", "nld", "dut", "Dutch"},
  { "", "dyu", "dyu", "Dyula"},
  { "dz", "dzo", "dzo", "Dzongkha"},
  { "", "efi", "efi", "Efik"},
  { "", "egy", "egy", "Egyptian (Ancient)"},
  { "", "eka", "eka", "Ekajuk"},
  { "", "elx", "elx", "Elamite"},
  { "", "enm", "enm", "English, Middle (1100-1500)"},
  { "", "ang", "ang", "English, Old (ca. 450-1100)"},
  { "en", "eng", "eng", "English"},
  { "eo", "epo", "epo", "Esperanto"},
  { "et", "est", "est", "Estonian"},
  { "", "eth", "eth", "Ethiopic"},
  { "", "ewe", "ewe", "Ewe"},
  { "", "ewo", "ewo", "Ewondo"},
  { "fo", "fao", "fao", "Faroese"},
  { "", "fan", "fan", "Fang"},
  { "", "fat", "fat", "Fanti"},
  { "fj", "fij", "fij", "Fijian"},
  { "fi", "fin", "fin", "Finnish"},
  { "", "fiu", "fiu", "Finno-Ugrian (Other)"},
  { "", "fon", "fon", "Fon"},
  { "", "frm", "frm", "French, Middle (ca. 1400-1600)"},
  { "", "fro", "fro", "French, Old (ca. 842-1400)"},
  { "fr", "fra", "fre", "French"},
  { "fy", "fry", "fry", "Frisian"},
  { "", "fur", "fur", "Friulian"},
  { "", "ful", "ful", "Fulah"},
  { "", "gaa", "gaa", "Ga"},
  { "gd", "gdh", "gae", "Gaelic (Scots)"},
  { "gl", "glg", "glg", "Gallegan"},
  { "", "lug", "lug", "Ganda"},
  { "", "gay", "gay", "Gayo"},
  { "", "gba", "gba", "Gbaya"},
  { "", "gez", "gez", "Geez"},
  { "ka", "kat", "geo", "Georgian"},
  { "", "gmh", "gmh", "German, Middle High (ca. 1050-1500)"},
  { "", "goh", "goh", "German, Old High (ca. 750-1050)"},
  { "de", "deu", "ger", "German"},
  { "", "gem", "gem", "Germanic (Other)"},
  { "", "gil", "gil", "Gilbertese"},
  { "", "gon", "gon", "Gondi"},
  { "", "gor", "gor", "Gorontalo"},
  { "", "got", "got", "Gothic"},
  { "", "grb", "grb", "Grebo"},
  { "", "grc", "grc", "Greek, Ancient (to 1453)"},
  { "el", "ell", "gre", "Greek, Modern (1453-)"},
  { "gn", "grn", "grn", "Guarani"},
  { "gu", "guj", "guj", "Gujarati"},
  { "", "gwi", "gwi", "Gwich'in"},
  { "", "hai", "hai", "Haida"},
  { "ha", "hau", "hau", "Hausa"},
  { "", "haw", "haw", "Hawaiian"},
  { "iw", "heb", "heb", "Hebrew"},
  { "", "her", "her", "Herero"},
  { "", "hil", "hil", "Hiligaynon"},
  { "", "him", "him", "Himachali"},
  { "hi", "hin", "hin", "Hindi"},
  { "", "hmo", "hmo", "Hiri Motu"},
  { "", "hit", "hit", "Hittite"},
  { "", "hmn", "hmn", "Hmong"},
  { "hu", "hun", "hun", "Hungarian"},
  { "", "hup", "hup", "Hupa"},
  { "", "iba", "iba", "Iban"},
  { "is", "isl", "ice", "Icelandic"},
  { "", "ibo", "ibo", "Igbo"},
  { "", "ijo", "ijo", "Ijo"},
  { "", "ilo", "ilo", "Iloko"},
  { "", "inc", "inc", "Indic (Other)"},
  { "", "ine", "ine", "Indo-European (Other)"},
  { "in", "ind", "ind", "Indonesian"},
  { "ia", "ina", "ina", "Interlingua (International Auxilary Language Association)"},
  { "ie", "ile", "ile", "Interlingue"},
  { "iu", "iku", "iku", "Inuktitut"},
  { "ik", "ipk", "ipk", "Inupiak"},
  { "", "ira", "ira", "Iranian (Other)"},
  { "", "mga", "mga", "Irish, Middle (900-1200)"},
  { "", "sga", "sga", "Irish, Old (to 900)"},
  { "ga", "gai", "iri", "Irish"},
  { "", "iro", "iro", "Iroquoian languages"},
  { "it", "ita", "ita", "Italian"},
  { "ja", "jpn", "jpn", "Japanese"},
  { "jw", "jaw", "jav", "Javanese"},
  { "", "jrb", "jrb", "Judeo-Arabic"},
  { "", "jpr", "jpr", "Judeo-Persian"},
  { "", "kab", "kab", "Kabyle"},
  { "", "kac", "kac", "Kachin"},
  { "kl", "kal", "kal", "Kalaallisut (Greenlandic)"},
  { "", "kam", "kam", "Kamba"},
  { "kn", "kan", "kan", "Kannada"},
  { "", "kau", "kau", "Kanuri"},
  { "", "kaa", "kaa", "Kara-Kalpak"},
  { "", "kar", "kar", "Karen"},
  { "ks", "kas", "kas", "Kashmiri"},
  { "", "kaw", "kaw", "Kawi"},
  { "kk", "kaz", "kaz", "Kazakh"},
  { "", "kha", "kha", "Khasi"},
  { "km", "khm", "khm", "Khmer"},
  { "", "khi", "khi", "Khoisan (Other)"},
  { "", "kho", "kho", "Khotanese"},
  { "", "kik", "kik", "Kikuyu"},
  { "", "kmb", "kmb", "Kimbundu"},
  { "rw", "kin", "kin", "Kinyarwanda"},
  { "ky", "kir", "kir", "Kirghiz"},
  { "", "kom", "kom", "Komi"},
  { "", "kon", "kon", "Kongo"},
  { "", "kok", "kok", "Konkani"},
  { "ko", "kor", "kor", "Korean"},
  { "", "kos", "kos", "Kosraean"},
  { "", "kpe", "kpe", "Kpelle"},
  { "", "kro", "kro", "Kru"},
  { "", "kua", "kua", "Kuanyama"},
  { "", "kum", "kum", "Kumyk"},
  { "ku", "kur", "kur", "Kurdish"},
  { "", "kru", "kru", "Kurukh"},
  { "", "kus", "kus", "Kusaie"},
  { "", "kut", "kut", "Kutenai"},
  { "", "lad", "lad", "Ladino"},
  { "", "lah", "lah", "Lahnda"},
  { "", "lam", "lam", "Lamba"},
  { "lo", "lao", "lao", "Lao"},
  { "la", "lat", "lat", "Latin"},
  { "lv", "lav", "lav", "Latvian"},
  { "", "ltz", "ltz", "Letzeburgesch"},
  { "", "lez", "lez", "Lezghian"},
  { "ln", "lin", "lin", "Lingala"},
  { "lt", "lit", "lit", "Lithuanian"},
  { "", "loz", "loz", "Lozi"},
  { "", "lub", "lub", "Luba-Katanga"},
  { "", "lua", "lua", "Luba-Lulua"},
  { "", "lui", "lui", "Luiseno"},
  { "", "lun", "lun", "Lunda"},
  { "", "luo", "luo", "Luo (Kenya and Tanzania)"},
  { "", "lus", "lus", "Lushai"},
  { "mk", "mkd", "mac", "Macedonian"},
  { "", "mad", "mad", "Madurese"},
  { "", "mag", "mag", "Magahi"},
  { "", "mai", "mai", "Maithili"},
  { "", "mak", "mak", "Makasar"},
  { "mg", "mlg", "mlg", "Malagasy"},
  { "ms", "msa", "may", "Malay"},
  { "ml", "mal", "mal", "Malayalam"},
  { "mt", "mlt", "mlt", "Maltese"},
  { "", "mdr", "mdr", "Mandar"},
  { "", "man", "man", "Mandingo"},
  { "", "mni", "mni", "Manipuri"},
  { "", "mno", "mno", "Manobo languages"},
  { "", "max", "max", "Manx"},
  { "mi", "mri", "mao", "Maori"},
  { "mr", "mar", "mar", "Marathi"},
  { "", "chm", "chm", "Mari"},
  { "", "mah", "mah", "Marshall"},
  { "", "mwr", "mwr", "Marwari"},
  { "", "mas", "mas", "Masai"},
  { "", "myn", "myn", "Mayan languages"},
  { "", "men", "men", "Mende"},
  { "", "mic", "mic", "Micmac"},
  { "", "min", "min", "Minangkabau"},
  { "", "mis", "mis", "Miscellaneous languages"},
  { "", "moh", "moh", "Mohawk"},
  { "mo", "mol", "mol", "Moldavian"},
  { "", "mkh", "mkh", "Mon-Khmer (Other)"},
  { "", "lol", "lol", "Mongo"},
  { "mn", "mon", "mon", "Mongolian"},
  { "", "mos", "mos", "Mossi"},
  { "", "mul", "mul", "Multiple languages"},
  { "", "mun", "mun", "Munda languages"},
  { "na", "nau", "nau", "Nauru"},
  { "", "nav", "nav", "Navajo"},
  { "", "nde", "nde", "Ndebele, North"},
  { "", "nbl", "nbl", "Ndebele, South"},
  { "", "ndo", "ndo", "Ndonga"},
  { "ne", "nep", "nep", "Nepali"},
  { "", "new", "new", "Newari"},
  { "", "nia", "nia", "Nias"},
  { "", "nic", "nic", "Niger-Kordofanian (Other)"},
  { "", "ssa", "ssa", "Nilo-Saharan (Other)"},
  { "", "niu", "niu", "Niuean"},
  { "", "non", "non", "Norse, Old"},
  { "", "nai", "nai", "North American Indian (Other)"},
  { "no", "nor", "nor", "Norwegian"},
  { "", "nub", "nub", "Nubian languages"},
  { "", "nym", "nym", "Nyamwezi"},
  { "", "nya", "nya", "Nyanja"},
  { "", "nyn", "nyn", "Nyankole"},
  { "", "nyo", "nyo", "Nyoro"},
  { "", "nzi", "nzi", "Nzima"},
  { "oc", "oci", "oci", "Occitan (post 1500)"},
  { "", "oji", "oji", "Ojibwa"},
  { "or", "ori", "ori", "Oriya"},
  { "om", "orm", "orm", "Oromo"},
  { "", "osa", "osa", "Osage"},
  { "", "oss", "oss", "Ossetic"},
  { "", "oto", "oto", "Otomian languages"},
  { "", "pal", "pal", "Pahlavi"},
  { "", "pau", "pau", "Palauan"},
  { "", "pli", "pli", "Pali"},
  { "", "pam", "pam", "Pampanga"},
  { "", "pag", "pag", "Pangasinan"},
  { "pa", "pan", "pan", "Panjabi"},
  { "", "pap", "pap", "Papiamento"},
  { "", "paa", "paa", "Papuan (Other)"},
  { "", "peo", "peo", "Persian, Old (ca. 600-400 B.C.)"},
  { "fa", "fas", "per", "Persian"},
  { "", "phi", "phi", "Philippine (Other)"},
  { "", "phn", "phn", "Phoenician"},
  { "", "pon", "pon", "Pohnpeian"},
  { "pl", "pol", "pol", "Polish"},
  { "pt", "por", "por", "Portuguese"},
  { "", "pra", "pra", "Prakrit languages"},
  { "", "pro", "pro", "Provençal, Old (to 1500)"},
  { "ps", "pus", "pus", "Pushto"},
  { "qu", "que", "que", "Quechua"},
  { "rm", "roh", "roh", "Rhaeto-Romance"},
  { "", "raj", "raj", "Rajasthani"},
  { "", "rap", "rap", "Rapanui"},
  { "", "rar", "rar", "Rarotongan"},
  { "", "roa", "roa", "Romance (Other)"},
  { "ro", "ron", "rum", "Romanian"},
  { "", "rom", "rom", "Romany"},
  { "rn", "run", "run", "Rundi"},
  { "ru", "rus", "rus", "Russian"},
  { "", "sal", "sal", "Salishan languages"},
  { "", "sam", "sam", "Samaritan Aramaic"},
  { "", "smi", "smi", "Sami languages"},
  { "sm", "smo", "smo", "Samoan"},
  { "", "sad", "sad", "Sandawe"},
  { "sg", "sag", "sag", "Sango"},
  { "sa", "san", "san", "Sanskrit"},
  { "", "sat", "sat", "Santali"},
  { "", "srd", "srd", "Sardinian"},
  { "", "sas", "sas", "Sasak"},
  { "", "sco", "sco", "Scots"},
  { "", "sel", "sel", "Selkup"},
  { "", "sem", "sem", "Semitic (Other)"},
  { "sr", "srp", "scc", "Serbian"},
  { "sh", "scr", "scr", "Serbo-Croatian"},
  { "", "srr", "srr", "Serer"},
  { "", "shn", "shn", "Shan"},
  { "sn", "sna", "sna", "Shona"},
  { "", "sid", "sid", "Sidamo"},
  { "", "bla", "bla", "Siksika"},
  { "sd", "snd", "snd", "Sindhi"},
  { "si", "sin", "sin", "Singhalese"},
  { "", "sit", "sit", "Sino-Tibetan (Other)"},
  { "", "sio", "sio", "Siouan languages"},
  { "ss", "ssw", "ssw", "Siswant"},
  { "", "den", "den", "Slave (Athapascan)"},
  { "", "sla", "sla", "Slavic (Other)"},
  { "sk", "slk", "slo", "Slovak"},
  { "sl", "slv", "slv", "Slovenian"},
  { "", "sog", "sog", "Sogdian"},
  { "", "nso", "nso", "Sotho, Northern"},
  { "so", "som", "som", "Somali"},
  { "", "son", "son", "Songhai"},
  { "", "snk", "snk", "Soninke"},
  { "", "wen", "wen", "Sorbian languages"},
  { "st", "sot", "sot", "Sotho, Southern"},
  { "", "sai", "sai", "South American Indian (Other)"},
  { "es", "spa", "spa", "Spanish"},
  { "su", "sun", "sun", "Sudanese"},
  { "", "suk", "suk", "Sukuma"},
  { "", "sux", "sux", "Sumerian"},
  { "", "sus", "sus", "Susu"},
  { "sw", "swa", "swa", "Swahili"},
  { "", "ssw", "ssw", "Swati"},
  { "sv", "swe", "swe", "Swedish"},
  { "", "syr", "syr", "Syriac"},
  { "tl", "tgl", "tgl", "Tagalog"},
  { "", "tah", "tah", "Tahitian"},
  { "", "tai", "tai", "Tai (Other)"},
  { "tg", "tgk", "tgk", "Tajik"},
  { "", "tmh", "tmh", "Tamashek"},
  { "ta", "tam", "tam", "Tamil"},
  { "tt", "tat", "tat", "Tatar"},
  { "te", "tel", "tel", "Telugu"},
  { "", "ter", "ter", "Tereno"},
  { "", "tet", "tet", "Tetum"},
  { "th", "tha", "tha", "Thai"},
  { "bo", "bod", "tib", "Tibetan"},
  { "", "tig", "tig", "Tigre"},
  { "ti", "tir", "tir", "Tigrinya"},
  { "", "tem", "tem", "Timne"},
  { "", "tiv", "tiv", "Tiv"},
  { "", "tli", "tli", "Tlingit"},
  { "", "tpi", "tpi", "Tok Pisin"},
  { "", "tkl", "tkl", "Tokelau"},
  { "to", "tog", "tog", "Tonga (Nyasa)"},
  { "", "ton", "ton", "Tonga (Tonga Islands)"},
  { "", "tsi", "tsi", "Tsimshian"},
  { "ts", "tso", "tso", "Tsonga"},
  { "tn", "tsn", "tsn", "Tswana"},
  { "", "tum", "tum", "Tumbuka"},
  { "", "ota", "ota", "Turkish, Ottoman (1500-1928)"},
  { "tr", "tur", "tur", "Turkish"},
  { "tk", "tuk", "tuk", "Turkmen"},
  { "", "tvl", "tvl", "Tuvalu"},
  { "", "tyv", "tyv", "Tuvinian"},
  { "tw", "twi", "twi", "Twi"},
  { "", "uga", "uga", "Ugaritic"},
  { "ug", "uig", "uig", "Uighur"},
  { "uk", "ukr", "ukr", "Ukrainian"},
  { "", "umb", "umb", "Umbundu"},
  { "", "und", "und", "Undetermined"},
  { "ur", "urd", "urd", "Urdu"},
  { "uz", "uzb", "uzb", "Uzbek"},
  { "", "vai", "vai", "Vai"},
  { "", "ven", "ven", "Venda"},
  { "vi", "vie", "vie", "Vietnamese"},
  { "vo", "vol", "vol", "Volapük"},
  { "", "vot", "vot", "Votic"},
  { "", "wak", "wak", "Wakashan languages"},
  { "", "wal", "wal", "Walamo"},
  { "", "war", "war", "Waray"},
  { "", "was", "was", "Washo"},
  { "cy", "cym", "wel", "Welsh"},
  { "wo", "wol", "wol", "Wolof"},
  { "xh", "xho", "xho", "Xhosa"},
  { "", "yao", "yao", "Yao"},
  { "", "yap", "yap", "Yapese"},
  { "ji", "yid", "yid", "Yiddish"},
  { "yo", "yor", "yor", "Yoruba"},
  { "", "ypk", "ypk", "Yupik languages"},
  { "", "znd", "znd", "Zande"},
  { "", "zap", "zap", "Zapotec"},
  { "", "zen", "zen", "Zenaga"},
  { "za", "zha", "zha", "Zhuang"},
  { "zu", "zul", "zul", "Zulu"},
  { "", "zun", "zun", "Zuni"},
