# Generated automatically from Makefile.in by configure.

TOPSRCDIR = .
TOPOBJ    = .
SRCDIR    = .


SUBDIRS = src mpk fonts scripts maps latex help stencils

all: build

build:
	for dir in $(SUBDIRS); do (cd $$dir; $(MAKE) -k); done

install:
	for dir in $(SUBDIRS); do (cd $$dir; $(MAKE) -k install); done

clean:
	for dir in $(SUBDIRS); do (cd $$dir; $(MAKE) clean); done

depend:
	for dir in $(SUBDIRS); do (cd $$dir; $(MAKE) depend); done
