#ifndef MP_HELPFILE_H
#define MP_HELPFILE_H
/*****************************************************************
**
** MathSpad 0.60
**
** Copyright 1996, Eindhoven University of Technology (EUT)
** 
********************************************************************/
#define CONSOLEHELP 0
#define CONSOLEWINDOWHELP 1
#define CONSOLEEDITOPHELP 2
#define CONSOLESTRUCTUREHELP 3
#define CONSOLESELECTIONHELP 4
#define CONSOLEMISCHELP 5
#define CONSOLEVERSIONHELP 6
#define CONSOLEQUITHELP 7

#define EDITHELP 10
#define EDITLOADHELP 11
#define EDITSAVEHELP 12 
#define EDITRENAMEHELP 13
#define EDITOUTPUTHELP 14
#define EDITINCLUDEHELP 15
#define EDITDONEHELP 16
#define EDITSUBHELP 17

#define FILESELCHELP 20
#define FILESELCOKHELP 21
#define FILESELCRESCANHELP 22
#define FILESELCCANCELHELP 23
#define FILESELCSELCHELP 24
#define FILESELCMASKHELP 25

#define STENCILHELP 30
#define STENCILLOADHELP 31
#define STENCILSAVEHELP 32
#define STENCILRENAMEHELP 33
#define STENCILDEFINEHELP 34
#define STENCILDONEHELP 35

#define DEFINEHELP 40
#define DEFINENEWHELP 41
#define DEFINEUPDATEHELP 42
#define DEFINEREMOVEHELP 43
#define DEFINEDOUBLEHELP 44
#define DEFINEDONEHELP 45
#define DEFINEPRECHELP 46
#define DEFINESPACEHELP 47
#define DEFINEKINDHELP 48
#define DEFINEPLACEHELP 49
#define DEFINETABSHELP 50
#define DEFINEMODEHELP 51
#define DEFINEFONTHELP 52
#define DEFINESIZEHELP 53
#define DEFINEMISCHELP 54
#define DEFINENAMEHELP 55
#define DEFINEHELPHELP 56
#define DEFINEVERSIONHELP 57

#define SYMBOLHELP 60
#define SYMBOLNEXTHELP 61
#define SYMBOLPREVHELP 62
#define SYMBOLDONEHELP 63

#define BUFFERHELP 70
#define BUFFERKILLHELP 71
#define BUFFERDONEHELP 72

#define FINDHELP 80
#define FINDFINDHELP 81
#define FINDSTACKHELP 82
#define FINDDONEHELP 83
#define FINDUPPERHELP 84
#define FINDLOWERHELP 85
#define FINDFINDPINUP 86
#define FINDSTACKPINUP 87

#define DEFAULTHELP 90
#define DEFAULTSETHELP 91
#define DEFAULTSAVEHELP 92
#define DEFAULTDONEHELP 93
#define DEFAULTSCREENHELP 94
#define DEFAULTLATEXHELP 95
#define DEFAULTDIRHELP 96
#define DEFAULTFONTHELP 97
#define DEFAULTKEYSHELP 98
#define DEFAULTSTIMEHELP 99
#define DEFAULTLMARGINHELP 100

#define BUTTONHELP 110
#define SCROLLBARHELP 111
#define PINUPHELP 112
#define KEYBOARDHELP 113
#define GETSTRINGHELP 114
#define POPUPHELP 115

#define CONSOLEWINDOWPINUP 120
#define CONSOLEEDITOPPINUP 121
#define CONSOLESTRUCTUREPINUP 122
#define CONSOLESELECTIONPINUP 123
#define CONSOLEMISCPINUP 124
#define CONSOLEVERSIONPINUP 125
#define CONSOLEQUITPINUP 126
#define CONSOLEJOINPINUP 127

#define MAXHELPNAME 130

extern char *helpname[MAXHELPNAME];
#endif
